/* Nexus Number V9 client — mobile-number collector */
(function(){
'use strict';
const API=String(window.NEXUS_NUMBER_API||'https://nexus-number-api.longyxs999.workers.dev').replace(/\/$/,'');
const KEY='nexus_number_v9';
const DROPS=[
 {key:'common',label:'Обычный',pct:65,oneIn:'1 к 1,54'},
 {key:'uncommon',label:'Необычный',pct:20,oneIn:'1 к 5'},
 {key:'rare',label:'Редкий',pct:10,oneIn:'1 к 10'},
 {key:'epic',label:'Эпический',pct:4,oneIn:'1 к 25'},
 {key:'legendary',label:'Легендарный',pct:.9,oneIn:'1 к 111'},
 {key:'mythic',label:'Мифический',pct:.1,oneIn:'1 к 1 000'}
];
const COUNTRIES=[
 {key:'all',name:'Все страны',code:'GLOBAL'},
 {key:'ru',name:'Россия',code:'+7'}, {key:'us',name:'США',code:'+1'}, {key:'ca',name:'Канада',code:'+1'},
 {key:'gb',name:'Великобритания',code:'+44'}, {key:'de',name:'Германия',code:'+49'}, {key:'fr',name:'Франция',code:'+33'},
 {key:'fi',name:'Финляндия',code:'+358'}, {key:'tr',name:'Турция',code:'+90'}, {key:'ae',name:'ОАЭ',code:'+971'},
 {key:'jp',name:'Япония',code:'+81'}, {key:'au',name:'Австралия',code:'+61'}
];
const PATTERNS=[
 {key:'random',name:'Случайная'},{key:'pair',name:'Двойная пара'},{key:'triple',name:'Тройка'},{key:'mirror',name:'Зеркало'},
 {key:'stairs',name:'Лестница'},{key:'lucky777',name:'Lucky 777'},{key:'lucky999',name:'Lucky 999'},{key:'all',name:'Полный дубль'}
];
const DEFAULT={auth:null,me:null,current:null,inventory:[],attempts:0,best:0,history:[],rare:{common:0,uncommon:0,rare:0,epic:0,legendary:0,mythic:0},online:0,sound:true,theme:'dark',country:'all',pattern:'random',adminData:null};
let state=Object.assign({},DEFAULT,load());
let page='home',rolling=false,feedTimer=0,liveTimer=0;
function load(){try{return JSON.parse(localStorage.getItem(KEY)||'{}')||{}}catch{return {}}}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state))}catch{}}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function money(v){return Number(v||0).toLocaleString('ru-RU')+' ₽'}
function fmtPreview(){return state.country==='all'?'+7 777 777 77 77':(COUNTRIES.find(x=>x.key===state.country)||COUNTRIES[1]).code+' 777 777 77 77'}
async function api(path,opts={}){const headers={'content-type':'application/json',...(opts.headers||{})};if(state.auth)headers.authorization='Bearer '+state.auth;let r;try{r=await fetch(API+path,{...opts,headers})}catch{throw new Error('NETWORK_ERROR')}const d=await r.json().catch(()=>({}));if(!r.ok||d.ok===false)throw new Error(d.error||'SERVER_ERROR');return d}
function rarityCls(k){return k||'common'}
function backline(title){return `<div class="backline"><button id="backBtn" aria-label="Назад">‹</button><h1>${esc(title)}</h1></div>`}
function art(type){return `<div class="art ${type}">${type==='art-cards'?'<i></i><i></i><i></i>':type==='art-chart'?'<i></i><i></i><i></i><i></i>':''}</div>`}
function homeView(){return `<div class="hero"><span class="eyebrow">NEXUS NUMBER</span><h2>Охота за редкими номерами</h2><p>Генерируй игровые мобильные номера, собирай дорогие комбинации и поднимайся в мировом рейтинге.</p></div><div class="menu-grid">
<button class="tile wide" data-page="generator"><b>ГЕНЕРАТОР</b><span>Одна кнопка — новый номер из общего пула</span>${art('art-phone')}<em class="tile-note">${esc(state.current?.number||fmtPreview())}</em></button>
<button class="tile" data-page="collection"><b>КОЛЛЕКЦИЯ</b><span>Твои номера и продажа</span>${art('art-cards')}</button>
<button class="tile" data-action="profile"><b>ПРОФИЛЬ</b><span>${state.me?esc(state.me.username):'Войти в аккаунт'}</span>${art('art-trophy')}</button>
<button class="tile" data-page="rating"><b>РЕЙТИНГ</b><span>Лучшие игроки и самые дорогие находки</span>${art('art-chart')}</button>
<button class="tile" data-page="stats"><b>СТАТИСТИКА</b><span>Редкость, паттерны и рекорды</span>${art('art-paper')}</button>
<button class="tile" data-page="settings"><b>НАСТРОЙКИ</b><span>Звук, страна и режим генерации</span>${art('art-gear')}</button>
<button class="tile" data-action="promo"><b>ПРОМОКОД</b><span>Введи код и получи бонус</span>${art('art-promo')}</button>
${state.me?.isAdmin?'<button class="tile" data-page="admin"><b>АДМИН-ПАНЕЛЬ</b><span>Управление балансом, удачей и кодами</span>'+art('art-chart')+'</button>':''}
</div><section class="section"><div class="head"><div><h3>СЕЙЧАС В ИГРЕ</h3><span class="muted">Живые редкие находки</span></div><span class="chip">LIVE</span></div><div id="homeFeed" class="feed"><div class="empty">Загрузка…</div></div></section>`}
function generatorView(){const r=state.current||{number:fmtPreview(),rarityKey:'common',rarity:'Обычный',rarityPct:65,oneIn:'1 к 1,54',pattern:'Случайная',price:1000,country:'Игровой пул'};const logged=!!state.me;const selCountry=COUNTRIES.find(c=>c.key===state.country)||COUNTRIES[0];return `${backline('Генератор')}<section class="section generator-card"><div class="head"><span class="chip">${state.country==='all'?'Все страны':esc(selCountry.name)}</span><span class="muted">Генераций: ${state.attempts}</span></div><div id="stage" class="number-stage"><div class="stage-label">ИГРОВОЙ МОБИЛЬНЫЙ НОМЕР</div><div class="phone"><div class="phone-head"><span>NEXUS NUMBER</span><span>${esc(r.pattern||'Случайная')}</span></div><div id="numberMain" class="phone-num">${esc(r.number)}</div><div class="phone-foot"><span>${esc(r.country||selCountry.name)}</span><span>COLLECTIBLE</span></div></div><div class="result"><div><small>КОМБИНАЦИЯ</small><strong>${esc(r.pattern||'Случайная')}</strong></div><div class="rarity ${rarityCls(r.rarityKey)}">${esc(r.rarity||'Обычный')}</div></div><div class="price-line"><span>Стоимость номера</span><b>${money(r.price)}</b></div><div class="chance"><span>Шанс редкости</span><b>${esc(r.rarityPct??r.chancePct??0)}% · ${esc(r.oneIn||'—')}</b></div><div class="progress"><i style="width:${Math.min(100,(Math.log10(Math.max(1000,Number(r.price||1000)))/12)*100)}%"></i></div></div><button id="generateBtn" class="bigbutton" ${logged?'':'data-login="1"'}>${logged?'ГЕНЕРИРОВАТЬ':'ВОЙТИ И НАЧАТЬ'}<small>${logged?'1 000 ₽ за попытку · результат сохраняется в коллекции':'Аккаунт нужен, чтобы сохранить прогресс'}</small></button><div class="secondary"><button data-action="share">Поделиться</button><button data-page="collection">Моя коллекция</button></div></section><section class="section"><div class="head"><div><h3>НАСТРОЙКА ГЕНЕРАЦИИ</h3><span class="muted">Страна и тип комбинации</span></div><button class="chip" data-page="settings">Изменить</button></div><div class="settings-list" style="margin-top:8px"><div class="setting"><div><strong>Страна</strong><small>${esc(selCountry.name)}</small></div><b>${esc(selCountry.code)}</b></div><div class="setting"><div><strong>Паттерн</strong><small>${esc((PATTERNS.find(p=>p.key===state.pattern)||PATTERNS[0]).name)}</small></div><b>✦</b></div></div></section><section class="section"><div class="head"><div><h3>ПОСЛЕДНИЙ DROP</h3><span class="muted">Твоя последняя находка</span></div><span class="chip">${state.me?money(state.me.balance):'Войти'}</span></div><div id="recentMini" class="feed"><div class="empty">${state.current?esc(state.current.number):'Пока пусто'}</div></div></section><section class="section"><div class="head"><div><h3>LIVE</h3><span class="muted">Игроки выбивают редкие номера прямо сейчас</span></div><span class="chip">ONLINE</span></div><div id="generatorFeed" class="feed"><div class="empty">Загрузка…</div></div></section>`}
function collectionView(){const items=state.inventory||[];return `${backline('Коллекция')}<section class="section"><div class="head"><div><h3>ТВОЯ КОЛЛЕКЦИЯ</h3><span class="muted">${items.length} игровых номеров</span></div><span class="chip">${money(state.me?.balance||0)}</span></div><div id="inventory" class="list">${items.length?items.map(x=>`<div class="listrow"><div><strong>${esc(x.number)}</strong><small>${esc(x.rarity||'Обычный')} · ${esc(x.pattern||'Случайная')} · ${esc(x.createdAt?new Date(Number(x.createdAt)).toLocaleDateString('ru-RU'): '')}</small></div><div style="text-align:right"><b>${money(x.price)}</b><br><button class="sell" data-sell="${esc(x.id)}" data-price="${Number(x.price||0)}">Продать</button></div></div>`).join(''):'<div class="empty">Пока нет номеров. Открой генератор и попробуй удачу.</div>'}</div></section>`}
function ratingView(){return `${backline('Рейтинг')}<div class="hero"><span class="eyebrow">GLOBAL LEADERBOARD</span><h2>Самые дорогие номера</h2><p>Игроки соревнуются за лучшую находку.</p></div><section class="section"><div class="head"><h3>ТОП 100</h3><span class="chip"><span class="dot"></span>${state.online} онлайн</span></div><div id="leaderboard" class="list"><div class="empty">Загрузка рейтинга…</div></div></section>`}
function statsView(){const counts=state.rare||DEFAULT.rare;const total=Object.values(counts).reduce((a,b)=>a+Number(b||0),0);return `${backline('Статистика')}<section class="section"><div class="formgrid two"><div class="setting"><div><strong>Всего генераций</strong><small>На этом устройстве</small></div><b>${state.attempts}</b></div><div class="setting"><div><strong>Лучший номер</strong><small>Максимальная цена</small></div><b>${state.best?money(state.best):'—'}</b></div></div><div class="formgrid two" style="margin-top:7px"><div class="setting"><div><strong>Редких+</strong><small>Редкий и выше</small></div><b>${counts.rare+counts.epic+counts.legendary+counts.mythic}</b></div><div class="setting"><div><strong>В коллекции</strong><small>Сохранено онлайн</small></div><b>${state.me?.inventoryCount??state.inventory.length}</b></div></div></section><section class="section"><div class="head"><h3>РЕДКОСТЬ</h3><span class="muted">Базовый шанс</span></div>${DROPS.map(d=>`<div class="setting" style="margin-top:7px"><div style="flex:1"><strong>${d.label}</strong><div class="progress"><i style="width:${Math.min(100,d.pct)}%"></i></div></div><b>${d.pct}%</b></div>`).join('')}</section><section class="section"><div class="head"><h3>ТИПЫ КОМБИНАЦИЙ</h3><span class="muted">Редкость определяется сочетанием цифр</span></div>${PATTERNS.map(p=>`<div class="feedrow"><div><strong>${p.name}</strong><small>Игровой паттерн</small></div><b>✦</b></div>`).join('')}</section>`}
function settingsView(){return `${backline('Настройки')}<section class="section"><div class="settings-list"><div class="setting"><div><strong>Звук</strong><small>Звук после выпадения номера</small></div><button id="soundBtn" class="chip ${state.sound?'active':''}">${state.sound?'ВКЛ':'ВЫКЛ'}</button></div><div class="setting"><div><strong>Страна генерации</strong><small>Выбери один рынок или общий мировой пул</small></div><select id="countrySelect" class="select" style="width:180px">${COUNTRIES.map(c=>`<option value="${c.key}" ${state.country===c.key?'selected':''}>${esc(c.name)}</option>`).join('')}</select></div><div class="setting"><div><strong>Тип комбинации</strong><small>Случайно или конкретный паттерн</small></div><select id="patternSelect" class="select" style="width:180px">${PATTERNS.map(p=>`<option value="${p.key}" ${state.pattern===p.key?'selected':''}>${esc(p.name)}</option>`).join('')}</select></div><div class="setting"><div><strong>Аккаунт</strong><small>${state.me?esc(state.me.username):'Не выполнен вход'}</small></div><button class="chip" data-action="profile">${state.me?'Профиль':'Войти'}</button></div><div class="setting"><div><strong>История на устройстве</strong><small>Сбросить только локальные счётчики</small></div><button id="resetBtn" class="chip">Сброс</button></div></div></section>`}
function adminView(){if(!state.me?.isAdmin)return `${backline('Админ-панель')}<section class="section"><div class="empty">Доступ запрещён.</div></section>`;const d=state.adminData||{},l=d.luck||{globalMultiplier:1,globalUntil:0};return `${backline('Админ-панель')}<section class="section admin-grid"><div class="adminbox"><h3>ГЛОБАЛЬНАЯ УДАЧА</h3><div class="formgrid two"><input id="luckMultiplier" class="input" type="number" min="1" max="20" step=".1" value="${Number(l.globalMultiplier||1)}"><input id="luckDuration" class="input" type="number" min="0" max="43200" value="60"></div><button class="btn" id="luckApply" style="margin-top:7px">Применить</button></div><div class="adminbox"><h3>НАЧИСЛИТЬ БАЛАНС</h3><div class="formgrid two"><input id="grantUser" class="input" placeholder="Игрок"><input id="grantAmount" class="input" type="number" placeholder="Сумма"></div><button class="btn" id="grantApply" style="margin-top:7px">Начислить</button></div><div class="adminbox"><h3>СОЗДАТЬ ПРОМОКОД</h3><div class="formgrid two"><input id="promoCode" class="input" placeholder="NEXUS2026"><select id="promoRewardType" class="select"><option value="money">Деньги</option><option value="luck">Удача</option></select></div><div class="formgrid two" style="margin-top:7px"><input id="promoAmount" class="input" type="number" placeholder="Сумма"><input id="promoLuckValue" class="input" type="number" step=".01" placeholder="X удачи"></div><div class="formgrid two" style="margin-top:7px"><input id="promoDuration" class="input" type="number" placeholder="Минут удачи"><input id="promoMaxUses" class="input" type="number" placeholder="Лимит использований"></div><button class="btn" id="promoCreate" style="margin-top:7px">Создать</button></div><div class="adminbox"><h3>ПРОМОКОДЫ</h3>${(d.promos||[]).map(p=>`<div class="player"><div><strong>${esc(p.code)}</strong><small>${p.rewardType==='money'?money(p.amount):'Удача X'+Number(p.luckValue||1).toFixed(2)} · использований ${p.uses}/${p.maxUses||'∞'}</small></div><button class="btn" data-toggle-promo="${esc(p.id)}">${p.active?'ВЫКЛ':'ВКЛ'}</button></div>`).join('')||'<div class="empty">Промокодов пока нет</div>'}</div><div class="adminbox"><h3>ИГРОКИ</h3>${(d.players||[]).map(p=>`<div class="player"><div><strong>${esc(p.username)}</strong><small>${money(p.balance)} · ${p.inventoryCount} SIM · лучший ${money(p.bestPrice)}${p.online?' · ONLINE':''}</small></div><span class="chip">${p.isAdmin?'ADMIN':''}</span></div>`).join('')||'<div class="empty">Игроков нет</div>'}</div></section>`}
function render(){const v=document.getElementById('appView');if(!v)return;const titles={home:'ГЛАВНАЯ',generator:'ГЕНЕРАТОР',collection:'КОЛЛЕКЦИЯ',rating:'РЕЙТИНГ',stats:'СТАТИСТИКА',settings:'НАСТРОЙКИ',admin:'АДМИН-ПАНЕЛЬ'};document.getElementById('title').textContent=titles[page]||'NEXUS NUMBER';v.innerHTML=page==='home'?homeView():page==='generator'?generatorView():page==='collection'?collectionView():page==='rating'?ratingView():page==='stats'?statsView():page==='settings'?settingsView():adminView();document.querySelectorAll('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===page));renderTop();bind();if(page==='collection')loadInventory();if(page==='rating')loadLeaderboard();if(page==='generator'){loadFeed('generatorFeed');showRecent()}if(page==='home')loadFeed('homeFeed');if(page==='admin')loadAdmin();}
function renderTop(){const bal=document.getElementById('balanceTop');if(bal)bal.textContent=Number(state.me?.balance||0).toLocaleString('ru-RU');const online=document.getElementById('onlineCount');if(online)online.textContent=String(state.online||0);document.documentElement.dataset.theme=state.theme}
function bind(){document.querySelectorAll('[data-page]').forEach(b=>b.addEventListener('click',()=>navigate(b.dataset.page)));document.querySelectorAll('[data-action]').forEach(b=>b.addEventListener('click',()=>handleAction(b.dataset.action)));document.getElementById('backBtn')?.addEventListener('click',()=>navigate('home'));document.getElementById('generateBtn')?.addEventListener('click',e=>e.currentTarget.dataset.login?openAuth():generate());document.querySelectorAll('[data-sell]').forEach(b=>b.addEventListener('click',()=>sellItem(b.dataset.sell,Number(b.dataset.price||0))));document.getElementById('soundBtn')?.addEventListener('click',()=>{state.sound=!state.sound;save();render()});document.getElementById('countrySelect')?.addEventListener('change',e=>{state.country=e.target.value;save();render()});document.getElementById('patternSelect')?.addEventListener('change',e=>{state.pattern=e.target.value;save();render()});document.getElementById('resetBtn')?.addEventListener('click',()=>{state.attempts=0;state.best=0;state.history=[];state.rare=Object.assign({},DEFAULT.rare);save();toast('Локальная статистика сброшена')});document.getElementById('luckApply')?.addEventListener('click',adminLuck);document.getElementById('grantApply')?.addEventListener('click',adminBalance);document.getElementById('promoCreate')?.addEventListener('click',adminPromo);document.querySelectorAll('[data-toggle-promo]').forEach(b=>b.addEventListener('click',()=>adminTogglePromo(b.dataset.togglePromo)))}
function handleAction(a){if(a==='profile')openProfile();else if(a==='promo')openPromo();else if(a==='share')share()}
function navigate(p){page=p||'home';render();window.scrollTo({top:0,behavior:'instant'})}
function modal(html){const root=document.getElementById('modalRoot');root.innerHTML=`<div class="modalback" id="modalBack"><div class="modal">${html}</div></div>`;document.getElementById('modalBack').addEventListener('click',e=>{if(e.target.id==='modalBack')root.innerHTML=''});document.getElementById('modalClose')?.addEventListener('click',()=>root.innerHTML='')}
function openAuth(reg=false){modal(`<div class="modalhead"><h2>${reg?'Регистрация':'Вход'}</h2><button class="x" id="modalClose">×</button></div><div class="tabs"><button id="tabLogin" class="${reg?'':'on'}">Войти</button><button id="tabReg" class="${reg?'on':''}">Регистрация</button></div><div id="authForm"><div class="formgrid"><input id="loginName" class="input" autocomplete="username" placeholder="Логин"><input id="loginPass" class="input" type="password" autocomplete="current-password" placeholder="Пароль"><button id="authSubmit" class="submit">${reg?'Создать аккаунт':'Войти'}</button></div><div class="formnote">Аккаунт сохраняет баланс, коллекцию и место в рейтинге.</div></div>`);document.getElementById('tabLogin').onclick=()=>openAuth(false);document.getElementById('tabReg').onclick=()=>openAuth(true);document.getElementById('authSubmit').onclick=()=>authSubmit(reg)}
async function authSubmit(reg){const u=document.getElementById('loginName').value.trim(),p=document.getElementById('loginPass').value;if(u.length<3||p.length<6)return toast('Проверь логин и пароль');try{const d=await api(reg?'/api/register':'/api/login',{method:'POST',body:JSON.stringify({username:u,password:p})});state.auth=d.token;state.me=d.user;save();document.getElementById('modalRoot').innerHTML='';toast(reg?'Аккаунт создан':'Вход выполнен');navigate(page);startLive()}catch(e){const m={USERNAME_TAKEN:'Этот логин уже занят',INVALID_INPUT:'Логин 3–20 символов, пароль от 6',INVALID_CREDENTIALS:'Неверный логин или пароль',RATE_LIMITED:'Слишком много попыток, подожди немного',SERVICE_BUSY:'Сервис занят, попробуй через несколько секунд',SERVER_ERROR:'Не удалось обработать запрос',NETWORK_ERROR:'Нет соединения'};toast(m[e.message]||'Не удалось выполнить запрос')}}
function openProfile(){if(!state.me)return openAuth(false);modal(`<div class="modalhead"><h2>Профиль</h2><button class="x" id="modalClose">×</button></div><section class="section" style="margin-top:10px"><div class="setting"><div><strong>${esc(state.me.username)}</strong><small>Баланс</small></div><b>${money(state.me.balance)}</b></div><div class="setting" style="margin-top:7px"><div><strong>Лучший номер</strong><small>${esc(state.me.bestNumber||'—')}</small></div><b>${money(state.me.bestPrice||0)}</b></div><div class="setting" style="margin-top:7px"><div><strong>Удача</strong><small>Текущий множитель</small></div><b>X${Number(state.me.luckMultiplier||1).toFixed(2)}</b></div></section><div class="formgrid" style="margin-top:9px"><input id="displayName" class="input" value="${esc(state.me.username)}" placeholder="Имя"><button id="profileSave" class="submit">Сохранить имя</button><button id="logout" class="chip">Выйти из аккаунта</button></div>`);document.getElementById('profileSave').onclick=saveProfile;document.getElementById('logout').onclick=logout}
async function saveProfile(){const username=document.getElementById('displayName').value.trim();try{const d=await api('/api/profile',{method:'PATCH',body:JSON.stringify({username})});state.me=d.user;save();document.getElementById('modalRoot').innerHTML='';toast('Имя сохранено');render()}catch(e){toast(e.message==='INVALID_INPUT'?'Недопустимое имя':'Не удалось сохранить')}}
async function logout(){try{if(state.auth)await api('/api/logout',{method:'POST',body:'{}'})}catch{}state.auth=null;state.me=null;state.inventory=[];state.adminData=null;save();document.getElementById('modalRoot').innerHTML='';toast('Вы вышли');navigate('home')}
function openPromo(){if(!state.me)return openAuth(false);modal(`<div class="modalhead"><h2>Промокод</h2><button class="x" id="modalClose">×</button></div><div class="formgrid" style="margin-top:10px"><input id="promoInput" class="input" placeholder="Введи код"><button id="promoRedeem" class="submit">Активировать</button></div>`);document.getElementById('promoRedeem').onclick=redeemPromo}
async function redeemPromo(){const code=document.getElementById('promoInput').value.trim();if(!code)return toast('Введи код');try{const d=await api('/api/promo/redeem',{method:'POST',body:JSON.stringify({code})});state.me=d.user;save();document.getElementById('modalRoot').innerHTML='';toast(d.rewardType==='money'?`+${money(d.amount)}`:`Удача X${Number(d.luckValue||1).toFixed(2)} активирована`);render()}catch(e){const m={PROMO_NOT_FOUND:'Промокод не найден',PROMO_ALREADY_USED:'Ты уже использовал этот код',PROMO_EXPIRED:'Срок действия истёк',PROMO_LIMIT:'Лимит промокода исчерпан'};toast(m[e.message]||'Не удалось активировать код')}}
async function generate(){if(rolling)return;if(!state.me)return openAuth(false);rolling=true;const stage=document.getElementById('stage'),main=document.getElementById('numberMain'),btn=document.getElementById('generateBtn');btn.disabled=true;stage.classList.add('roll');const start=Date.now();const iv=setInterval(()=>{if(main){main.textContent=fmtPreview().replace(/\d/g,()=>Math.floor(Math.random()*10))}},55);try{const d=await api('/api/generate',{method:'POST',body:JSON.stringify({country:state.country,pattern:state.pattern})});const wait=Math.max(850-(Date.now()-start),120);setTimeout(()=>{clearInterval(iv);stage.classList.remove('roll');state.me=d.user;state.current=d.result;state.attempts++;state.best=Math.max(state.best,Number(d.result.price||0));state.rare[d.result.rarityKey]=(state.rare[d.result.rarityKey]||0)+1;state.history=[d.result,...state.history].slice(0,200);save();play(d.result.rarityKey==='mythic'||d.result.rarityKey==='legendary'?'rare':'normal');rolling=false;navigate('generator');toast(d.result.rarityKey==='mythic'?'МИФИЧЕСКИЙ DROP!':d.result.rarityKey==='legendary'?'ЛЕГЕНДАРНЫЙ НОМЕР!':'Номер добавлен в коллекцию');},wait)}catch(e){clearInterval(iv);stage.classList.remove('roll');rolling=false;btn.disabled=false;const m={INSUFFICIENT_BALANCE:'Недостаточно баланса',RATE_LIMITED:'Слишком быстро — подожди секунду',AUTH_REQUIRED:'Выполни вход',SERVICE_BUSY:'Сервис временно занят'};toast(m[e.message]||'Не удалось сгенерировать номер')}}
async function loadInventory(){if(!state.me)return;try{const d=await api('/api/inventory');state.inventory=d.items||[];state.me.balance=d.balance;state.me.inventoryCount=state.inventory.length;save();const root=document.getElementById('inventory');if(root)root.innerHTML=state.inventory.length?state.inventory.map(x=>`<div class=\"listrow\"><div><strong>${esc(x.number)}</strong><small>${esc(x.rarity||'Обычный')} · ${esc(x.pattern||'Случайная')} · ${esc(x.createdAt?new Date(Number(x.createdAt)).toLocaleDateString('ru-RU'):'')}</small></div><div style=\"text-align:right\"><b>${money(x.price)}</b><br><button class=\"sell\" data-sell=\"${esc(x.id)}\" data-price=\"${Number(x.price||0)}\">Продать</button></div></div>`).join(''):'<div class=\"empty\">Пока нет номеров. Открой генератор и попробуй удачу.</div>';bind();renderTop()}catch(e){toast('Не удалось загрузить коллекцию')}}
async function sellItem(id,price){if(!confirm(`Продать номер за ${money(Math.round(price*.8))}?`))return;try{const d=await api('/api/sell',{method:'POST',body:JSON.stringify({itemId:id})});state.me=d.user;save();await loadInventory();toast('Номер продан')}catch(e){toast(e.message==='ITEM_NOT_FOUND'?'Номер уже продан':'Не удалось продать')}}
function rankRow(x,i){return `<div class="listrow"><div><strong>#${i} · ${esc(x.username||'Игрок')}</strong><small>${esc(x.bestNumber||'—')} · ${esc(x.bestRarity||'—')} · ${x.online?'<span style="color:#4cc784">ONLINE</span>':'ОФЛАЙН'}</small></div><b>${money(x.bestPrice||0)}</b></div>`}
async function loadLeaderboard(){const root=document.getElementById('leaderboard');if(!root)return;try{const d=await api('/api/leaderboard?limit=100');state.online=Number(d.onlineCount||0);root.innerHTML=d.items?.length?d.items.map(rankRow).join(''):'<div class="empty">Пока игроков нет.</div>';save();renderTop()}catch{root.innerHTML='<div class="empty">Рейтинг временно недоступен.</div>'}}
async function loadFeed(id){const root=document.getElementById(id);if(!root)return;try{const d=await api('/api/feed?limit=10');root.innerHTML=d.items?.length?d.items.map(x=>`<div class="feedrow"><div><strong>${esc(x.username)} выбил ${esc(x.number)}</strong><small>${esc(x.rarity)} · ${esc(x.pattern)} · ${esc(x.createdAtText||'только что')}</small></div><b>${money(x.price)}</b></div>`).join(''):'<div class="empty">Редких находок пока нет.</div>'}catch{root.innerHTML='<div class="empty">Лента пока недоступна.</div>'}}
async function refreshOnline(){try{const d=await api('/api/online');state.online=Number(d.onlineCount||0);save();renderTop()}catch{}}
async function heartbeat(){if(!state.auth)return;try{await api('/api/heartbeat',{method:'POST',body:'{}'})}catch{}}
async function refreshMe(){if(!state.auth)return;try{const d=await api('/api/me');state.me=d.user;save();renderTop()}catch{state.auth=null;state.me=null;save()}}
function startLive(){clearInterval(feedTimer);clearInterval(liveTimer);refreshOnline();heartbeat();feedTimer=setInterval(()=>{refreshOnline();heartbeat()},60000);liveTimer=setInterval(()=>{if(page==='home')loadFeed('homeFeed');if(page==='generator')loadFeed('generatorFeed')},30000)}
async function showRecent(){const root=document.getElementById('recentMini');if(!root)return;root.innerHTML=state.current?`<div class="feedrow"><div><strong>${esc(state.current.number)}</strong><small>${esc(state.current.rarity)} · ${esc(state.current.pattern)}</small></div><b>${money(state.current.price)}</b></div>`:'<div class="empty">Пока пусто</div>'}
function play(kind){if(!state.sound)return;try{const C=window.AudioContext||window.webkitAudioContext;if(!C)return;const c=new C(),o=c.createOscillator(),g=c.createGain();o.connect(g);g.connect(c.destination);o.type='sine';o.frequency.value=kind==='rare'?760:300;g.gain.setValueAtTime(.0001,c.currentTime);g.gain.exponentialRampToValueAtTime(.045,c.currentTime+.02);g.gain.exponentialRampToValueAtTime(.0001,c.currentTime+(kind==='rare'?.4:.18));o.start();o.stop(c.currentTime+(kind==='rare'?.44:.21))}catch{}}
async function share(){if(!state.current)return toast('Сначала сгенерируй номер');const text=`${state.me?.username||'Игрок'} выбил ${state.current.number} — ${money(state.current.price)} · ${state.current.rarity}. Nexus Number`;try{if(navigator.share)return navigator.share({title:'Nexus Number',text});await navigator.clipboard.writeText(text);toast('Результат скопирован')}catch{toast('Не удалось поделиться')}}
async function loadAdmin(){if(!state.me?.isAdmin)return;try{const d=await api('/api/admin/data');state.adminData=d;save();if(page==='admin'){const v=document.getElementById('appView');if(v){v.innerHTML=adminView();bind();renderTop()}}}catch(e){toast(e.message==='ADMIN_REQUIRED'?'Доступ запрещён':'Не удалось загрузить админ-панель')}}
async function adminLuck(){try{const multiplier=Number(document.getElementById('luckMultiplier').value||1),durationMinutes=Math.floor(Number(document.getElementById('luckDuration').value||0));const d=await api('/api/admin/luck',{method:'POST',body:JSON.stringify({multiplier,durationMinutes})});state.adminData=state.adminData||{};state.adminData.luck=d.luck;save();toast('Удача обновлена');render()}catch{toast('Не удалось изменить удачу')}}
async function adminBalance(){const username=document.getElementById('grantUser').value.trim(),amount=Math.floor(Number(document.getElementById('grantAmount').value||0));if(!username||amount<1)return toast('Укажи игрока и сумму');try{await api('/api/admin/balance',{method:'POST',body:JSON.stringify({username,amount})});toast('Баланс начислен');await loadAdmin()}catch(e){toast(e.message==='PLAYER_NOT_FOUND'?'Игрок не найден':'Не удалось начислить баланс')}}
async function adminPromo(){const code=document.getElementById('promoCode').value.trim(),rewardType=document.getElementById('promoRewardType').value,amount=Math.floor(Number(document.getElementById('promoAmount').value||0)),luckValue=Number(document.getElementById('promoLuckValue').value||0),durationMinutes=Math.floor(Number(document.getElementById('promoDuration').value||0)),maxUses=Math.floor(Number(document.getElementById('promoMaxUses').value||0));try{const d=await api('/api/admin/promo',{method:'POST',body:JSON.stringify({code,rewardType,amount,luckValue,durationMinutes,maxUses,rewardMode:'x'})});toast('Промокод создан');await loadAdmin()}catch(e){toast(e.message==='PROMO_EXISTS'?'Такой код уже есть':'Не удалось создать код')}}
async function adminTogglePromo(id){try{await api('/api/admin/promo/toggle',{method:'POST',body:JSON.stringify({id})});await loadAdmin()}catch{toast('Не удалось изменить код')}}
function toast(msg){const t=document.getElementById('toast');t.textContent=msg;t.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove('show'),2200)}
document.getElementById('menuBtn').addEventListener('click',()=>navigate('home'));
document.getElementById('themeBtn').addEventListener('click',()=>{state.theme=state.theme==='dark'?'light':'dark';save();renderTop()});
(async function boot(){await refreshMe();render();startLive();window.NEXUS_NUMBER_BOOTED=true})();
})();
